// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrMeBTtN2wwqJbJx_hwXv58ocirb-V9xU',
    appId: '1:873026019407:web:e7c33805539eef594f8a3a',
    messagingSenderId: '873026019407',
    projectId: 'gestlife-8c548',
    authDomain: 'gestlife-8c548.firebaseapp.com',
    storageBucket: 'gestlife-8c548.appspot.com',
    measurementId: 'G-VRTG04KF00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPTziu47luHW-CNJc4r7Fw4sqptiW8RKc',
    appId: '1:873026019407:android:9deac6e76866678e4f8a3a',
    messagingSenderId: '873026019407',
    projectId: 'gestlife-8c548',
    storageBucket: 'gestlife-8c548.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ7KKsu-I5DJteYKNLvvHJvBtofZdWp14',
    appId: '1:873026019407:ios:e9554ec3a534cd2c4f8a3a',
    messagingSenderId: '873026019407',
    projectId: 'gestlife-8c548',
    storageBucket: 'gestlife-8c548.appspot.com',
    iosBundleId: 'com.example.gestLife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ7KKsu-I5DJteYKNLvvHJvBtofZdWp14',
    appId: '1:873026019407:ios:e9554ec3a534cd2c4f8a3a',
    messagingSenderId: '873026019407',
    projectId: 'gestlife-8c548',
    storageBucket: 'gestlife-8c548.appspot.com',
    iosBundleId: 'com.example.gestLife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrMeBTtN2wwqJbJx_hwXv58ocirb-V9xU',
    appId: '1:873026019407:web:cfd053fd6f60dcc54f8a3a',
    messagingSenderId: '873026019407',
    projectId: 'gestlife-8c548',
    authDomain: 'gestlife-8c548.firebaseapp.com',
    storageBucket: 'gestlife-8c548.appspot.com',
    measurementId: 'G-DC5BVR8NZ5',
  );
}
